[package]
name = "command"
version = "0.1.0"
authors = ["Kyle Gretchev <kgretchev@gmail.com>"]

[dependencies]
color_printer = { path = "../color_printer" }
command_derive = { path = "../command_derive" }
gitlib = { path = "../gitlib" }
