[package]
name = "manifestlib"
version = "0.1.0"
authors = ["Kyle Gretchev <kgretchev@gmail.com>"]

[dependencies]
serde = "1.0.2"
serde_json = "1.0.1"
serde_derive = "1.0.2"
gitlib = { path = "../gitlib" }