[package]
name = "command_mods"
version = "0.1.0"
authors = ["Kyle Gretchev <kyle.gretchev@magnetforensics.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1"

[dependencies.syn]
version = "1"
default-features = false
features = [
    "proc-macro"
]
