[package]
edition = "2018"
name = "gitlib"
version = "0.1.0"
authors = ["Kyle Gretcehv <kgretchev@gmail.com>"]

[dependencies]
git2 = "0.9"
ssh-config = { git = "https://github.com/devnought/ssh-config" }
url = "2"
