[package]
edition = "2018"
name = "command_derive"
version = "0.1.0"
authors = ["Kyle Gretchev <kgretchev@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
quote = "1"

[dependencies.syn]
version = "1"
